[build]
  base = "vd-web"
  command = "npm run build"
  publish = "dist"

  # 构建时使用的环境变量
  [build.environment]
    VITE_RESOURCE_DOMAIN="https://video-dns.wu.xingk.xyz​"

# 支持 HTML5 History 路由（SPA）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false